apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
     app: kibana
  replicas: 1 
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.3.0
        ports:
        - containerPort: 9200
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-0.es.default.svc.cluster.local:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "changeme"
---
apiVersion: v1
kind: Service
metadata:  
  name: kibana
spec:
  selector:
    app: kibana 
  type: NodePort
  ports:  
  - port: 5601
    name: ui
    targetPort: 5601
    nodePort: 31601
    protocol: TCP 

