apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
     app: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.5.8
        ports:
        - containerPort: 11211
---

apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  selector:
    app: memcached
  type: NodePort
  ports:
  - port: 11211
    targetPort: 11211
    nodePort: 31211
    protocol: TCP

