---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
     app: postgres
  replicas: 1 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        imagePullPolicy: Always
        image: postgres:10
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
---          
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 31543
