---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
---
apiVersion: v1
kind: Service
metadata:  
  name: rabbitmq
spec:
  selector:
    app: rabbitmq 
  type: NodePort
  ports:  
  - port: 5672
    name: rabbit
    targetPort: 5672
    nodePort: 31672
    protocol: TCP
  - port: 15672
    name: rabbit-mgmt
    targetPort: 15672
    nodePort: 31673
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
     app: rabbitmq
  replicas: 1 
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq 
        image: rabbitmq:3.7.5-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - configMapRef:
            name: rabbitmq-config
